### Project Overview
- As AI and automation change how we work, both companies and employees face uncertainty. Companies want to know how these changes affect job security, while employees worry about what might put their jobs at risk. Factors like experience, education, job role, company size, and how much AI is used can all matter, but their effects are not always clear. This project looks at real employee data to find useful patterns and builds a model to predict layoff risk. The goal is to help companies make better decisions and support employees in preparing for a changing, AI-driven future.

# Phase 1: Data Understanding & Preparation
- Before analyzing layoff risk, we need to determine whether the dataset is complete, accurate, and reliable. Poor-quality data can lead to misleading insights and unreliable business decisions.

### Section 1: Import Required Libraries

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### Section 2: Load Dataset

In [4]:
df = pd.read_csv(r"C:\Users\Anshu\OneDrive\Desktop\AI Adoption & Layoff Risk Analysis\Data\Ai_Impact_jobs_Layoff_Risk_Dataset.csv")
df.head()

,Age,Education_Level,Years_of_Experience,Industry,Job_Role,Company_Size,Job_Level,Routine_Task_Percentage,Creativity_Requirement,Human_Interaction_Level,AI_Adoption_Level,Number_of_AI_Tools_Used,AI_Usage_Hours_Per_Week,Tasks_Automated_Percentage,AI_Training_Hours,Layoff_Risk
0,59,Master's,6,Finance,Accountant,Medium,Entry,84,21,94,Medium,5,7,40,26,High
1,44,Master's,14,Manufacturing,Production Supervisor,Small,Entry,30,84,68,Low,2,2,14,9,Low
2,36,Bachelor's,7,Retail,Store Manager,Medium,Senior,12,86,71,Low,0,1,6,3,Low
3,27,Bachelor's,6,Finance,Auditor,Large,Entry,90,18,21,Medium,3,10,67,26,High
4,49,High School,12,Finance,Auditor,Small,Entry,49,52,72,Medium,5,13,26,19,Medium

### Section 3: Initial Dataset Overview

In [5]:
# Shape ---> Find Total Numbers of Rows & Columns Present
display(df.shape)
display(f'Rows: {df.shape[0]}')
display(f'Columns: {df.shape[1]}')

(20000, 16)

'Rows: 20000'

'Columns: 16'

- Dataset contains 20000 employee records and 16 variables

In [6]:
# Column names
df.columns.to_list()   # to_list() ---> It is used to show the columns names vertically.

['Age',
 'Education_Level',
 'Years_of_Experience',
 'Industry',
 'Job_Role',
 'Company_Size',
 'Job_Level',
 'Routine_Task_Percentage',
 'Creativity_Requirement',
 'Human_Interaction_Level',
 'AI_Adoption_Level',
 'Number_of_AI_Tools_Used',
 'AI_Usage_Hours_Per_Week',
 'Tasks_Automated_Percentage',
 'AI_Training_Hours',
 'Layoff_Risk']

In [7]:
# Data Types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Age                         20000 non-null  int64
 1   Education_Level             20000 non-null  object
 2   Years_of_Experience         20000 non-null  int64
 3   Industry                    20000 non-null  object
 4   Job_Role                    20000 non-null  object
 5   Company_Size                20000 non-null  object
 6   Job_Level                   20000 non-null  object
 7   Routine_Task_Percentage     20000 non-null  int64
 8   Creativity_Requirement      20000 non-null  int64
 9   Human_Interaction_Level     20000 non-null  int64
 10  AI_Adoption_Level           20000 non-null  object
 11  Number_of_AI_Tools_Used     20000 non-null  int64
 12  AI_Usage_Hours_Per_Week     20000 non-null  int64
 13  Tasks_Automated_Percentage  20000 non-null  int64
 14  AI_Training_Hours           20000 non-null  int64
 15  Layoff_Risk                 20000 non-null  object
dtypes: int64(9), object(7)
memory usage: 2.4+ MB

- Both Numerical & Categorical variables present in the dataset

In [8]:
# Display First & Last records

display(df.head(3))
display(df.tail(3))

,Age,Education_Level,Years_of_Experience,Industry,Job_Role,Company_Size,Job_Level,Routine_Task_Percentage,Creativity_Requirement,Human_Interaction_Level,AI_Adoption_Level,Number_of_AI_Tools_Used,AI_Usage_Hours_Per_Week,Tasks_Automated_Percentage,AI_Training_Hours,Layoff_Risk
0,59,Master's,6,Finance,Accountant,Medium,Entry,84,21,94,Medium,5,7,40,26,High
1,44,Master's,14,Manufacturing,Production Supervisor,Small,Entry,30,84,68,Low,2,2,14,9,Low
2,36,Bachelor's,7,Retail,Store Manager,Medium,Senior,12,86,71,Low,0,1,6,3,Low

,Age,Education_Level,Years_of_Experience,Industry,Job_Role,Company_Size,Job_Level,Routine_Task_Percentage,Creativity_Requirement,Human_Interaction_Level,AI_Adoption_Level,Number_of_AI_Tools_Used,AI_Usage_Hours_Per_Week,Tasks_Automated_Percentage,AI_Training_Hours,Layoff_Risk
19997,28,High School,7,Telecom,Support Specialist,Medium,Entry,91,2,49,Medium,2,14,55,10,High
19998,46,Bachelor's,3,Manufacturing,Quality Engineer,Medium,Senior,76,40,89,Medium,3,13,66,5,Medium
19999,36,Bachelor's,5,Retail,Store Manager,Medium,Mid,45,65,75,Low,1,0,30,8,Medium

- The target variable is Layoff_Risk with three categories.
  - High
  - Medium
  - Low

In [9]:
# Statistical Summary

df.describe().T     # .T ---> It is used to transpose the rows into columns and vice versa for better visual

,count,mean,std,min,25%,50%,75%,max
Age,20000.0,40.36150,11.526333,21.0,30.0,40.0,50.0,60.0
Years_of_Experience,20000.0,7.26550,4.720606,0.0,4.0,7.0,11.0,32.0
Routine_Task_Percentage,20000.0,51.88550,24.437808,10.0,31.0,52.0,73.0,94.0
Creativity_Requirement,20000.0,47.78670,26.100482,0.0,27.0,48.0,69.0,100.0
Human_Interaction_Level,20000.0,60.05500,22.267801,20.0,41.0,62.0,79.0,99.0
Number_of_AI_Tools_Used,20000.0,2.46035,2.097486,0.0,1.0,2.0,4.0,10.0
AI_Usage_Hours_Per_Week,20000.0,6.77395,6.086370,0.0,2.0,5.0,10.0,30.0
Tasks_Automated_Percentage,20000.0,37.22895,19.995120,4.0,21.0,35.0,51.0,93.0
AI_Training_Hours,20000.0,12.62140,13.552647,0.0,4.0,8.0,18.0,79.0

### Create Data Dictionary
- A data dictionary was created to provide a clear understanding of each variable used in the analysis. It defines the purpose, data type, business category, and expected values for every feature in the dataset. This documentation improves transparency and ensures consistent interpretation of the data throughout the project.

In [10]:
data_dictionary = pd.DataFrame({

    "Column Name":[
        "age",
        "education_level",
        "years_of_experience",
        "industry",
        "job_role",
        "company_size",
        "job_level",
        "routine_task_percentage",
        "creativity_requirement",
        "human_interaction_level",
        "ai_adoption_level",
        "number_of_ai_tools_used",
        "ai_usage_hours_per_week",
        "tasks_automated_percentage",
        "ai_training_hours",
        "layoff_risk"
    ],

    "Data Type":[
        "Integer",
        "Categorical",
        "Integer",
        "Categorical",
        "Categorical",
        "Categorical",
        "Categorical",
        "Numeric",
        "Numeric",
        "Numeric",
        "Categorical",
        "Integer",
        "Numeric",
        "Numeric",
        "Numeric",
        "Categorical"
    ],

    "Business Category":[
        "Employee Profile",
        "Employee Profile",
        "Employee Profile",
        "Organization",
        "Job Characteristics",
        "Organization",
        "Job Characteristics",
        "Job Characteristics",
        "Job Characteristics",
        "Job Characteristics",
        "AI Adoption",
        "AI Adoption",
        "AI Adoption",
        "AI Adoption",
        "AI Adoption",
        "Target Variable"
    ],

    "Business Description":[
        "Employee age",
        "Highest education completed",
        "Professional work experience",
        "Industry where employee works",
        "Current job role",
        "Organization size",
        "Employee seniority level",
        "Percentage of routine work",
        "Creativity required in job",
        "Human interaction required",
        "Company AI adoption level",
        "Number of AI tools used",
        "Weekly AI usage hours",
        "Percentage of work automated",
        "Hours of AI training",
        "Employee layoff risk"
    ]
})

data_dictionary

,Column Name,Data Type,Business Category,Business Description
0,age,Integer,Employee Profile,Employee age
1,education_level,Categorical,Employee Profile,Highest education completed
2,years_of_experience,Integer,Employee Profile,Professional work experience
3,industry,Categorical,Organization,Industry where employee works
4,job_role,Categorical,Job Characteristics,Current job role
5,company_size,Categorical,Organization,Organization size
6,job_level,Categorical,Job Characteristics,Employee seniority level
7,routine_task_percentage,Numeric,Job Characteristics,Percentage of routine work
8,creativity_requirement,Numeric,Job Characteristics,Creativity required in job
9,human_interaction_level,Numeric,Job Characteristics,Human interaction required
10,ai_adoption_level,Categorical,AI Adoption,Company AI adoption level
11,number_of_ai_tools_used,Integer,AI Adoption,Number of AI tools used
12,ai_usage_hours_per_week,Numeric,AI Adoption,Weekly AI usage hours
13,tasks_automated_percentage,Numeric,AI Adoption,Percentage of work automated
14,ai_training_hours,Numeric,AI Adoption,Hours of AI training
15,layoff_risk,Categorical,Target Variable,Employee layoff risk

### Check Data Quality
- A comprehensive data quality assessment was conducted to evaluate the completeness, consistency, validity, and reliability of the dataset. The objective of this step is to identify potential issues that could affect analytical results before performing exploratory analysis.

In [11]:
# Checking Missing Values

df.isnull().sum()

Age                           0
Education_Level               0
Years_of_Experience           0
Industry                      0
Job_Role                      0
Company_Size                  0
Job_Level                     0
Routine_Task_Percentage       0
Creativity_Requirement        0
Human_Interaction_Level       0
AI_Adoption_Level             0
Number_of_AI_Tools_Used       0
AI_Usage_Hours_Per_Week       0
Tasks_Automated_Percentage    0
AI_Training_Hours             0
Layoff_Risk                   0
dtype: int64

- No missing values were identified across any of the variables, indicating a complete dataset suitable for further analysis.

In [12]:
# Check Duplicate Records

df.duplicated().sum()

np.int64(0)

- No duplicate records found across the dataset, indicating that each row represent unique employee record.

In [13]:
# Unique Categories ----> count each categorical variable values

categories_cols = df.select_dtypes(include="object").columns

for col in categories_cols:

    print("="*60)
    print(col.upper())
    print("="*60)

    display(df[col].value_counts())

============================================================
EDUCATION_LEVEL
============================================================

Education_Level
Bachelor's     9967
Master's       5426
High School    3558
PhD            1049
Name: count, dtype: int64

============================================================
INDUSTRY
============================================================

Industry
Telecom          2582
Healthcare       2561
Finance          2513
Logistics        2488
IT               2483
Retail           2467
Manufacturing    2457
Education        2449
Name: count, dtype: int64

============================================================
JOB_ROLE
============================================================

Job_Role
Nurse                    900
Medical Assistant        889
Financial Analyst        879
Support Specialist       873
Network Engineer         862
Operator                 858
Inventory Analyst        857
Supply Chain Analyst     857
Data Analyst             849
Operations Analyst       847
Warehouse Manager        843
Software Engineer        829
Accountant               821
Academic Coordinator     819
Research Assistant       818
Auditor                  813
Teacher                  812
Sales Associate          807
Production Supervisor    806
ML Engineer              805
Store Manager            803
Quality Engineer         793
Dispatcher               788
Health Analyst           772
Name: count, dtype: int64

============================================================
COMPANY_SIZE
============================================================

Company_Size
Medium    8964
Small     6066
Large     4970
Name: count, dtype: int64

============================================================
JOB_LEVEL
============================================================

Job_Level
Entry     9016
Mid       7940
Senior    3044
Name: count, dtype: int64

============================================================
AI_ADOPTION_LEVEL
============================================================

AI_Adoption_Level
Low       10539
Medium     8046
High       1415
Name: count, dtype: int64

============================================================
LAYOFF_RISK
============================================================

Layoff_Risk
High      6797
Low       6602
Medium    6601
Name: count, dtype: int64

In [14]:
# convert the columns name into lowercase, because it helpful for analysis

df.columns = df.columns.str.lower()
df.columns.to_list()

['age',
 'education_level',
 'years_of_experience',
 'industry',
 'job_role',
 'company_size',
 'job_level',
 'routine_task_percentage',
 'creativity_requirement',
 'human_interaction_level',
 'ai_adoption_level',
 'number_of_ai_tools_used',
 'ai_usage_hours_per_week',
 'tasks_automated_percentage',
 'ai_training_hours',
 'layoff_risk']

### Range Validation
- It is required to check the validation rrule of percentage--->percentage should not > 100 or < 0

In [15]:
percent_columns = ['routine_task_percentage',
                  'creativity_requirement', 
                  'human_interaction_level',
                   'tasks_automated_percentage']
for col in percent_columns:
    invalid = df[(df[col]<0)|(df[col]>100)]   # ---> check is there any value not present in the dataset above 100 or below 0, because if present it violet the percentage validation
    print(f'{col}: {len(invalid)} invalid records')

routine_task_percentage: 0 invalid records
creativity_requirement: 0 invalid records
human_interaction_level: 0 invalid records
tasks_automated_percentage: 0 invalid records

### Logical Consistency
- It is important to check logically consistency which is not possible in actually.

In [16]:
# Lets take a example suppose in my dataset any of employee age is given like 25 and their years of experience should be given like 20---> it is logically incorrect data

invalid_experience = df[df['years_of_experience'] > (df['age']-18)]

df.groupby("job_level")["years_of_experience"].describe()
df.groupby('ai_adoption_level')['ai_usage_hours_per_week'].describe()

                     count       mean       std   min   25%   50%   75%   max
ai_adoption_level
High                1415.0  22.695406  4.641590  15.0  19.0  23.0  27.0  30.0
Low                10539.0   2.508872  1.707161   0.0   1.0   3.0   4.0   5.0
Medium              8046.0   9.560527  2.881156   5.0   7.0  10.0  12.0  14.0

### Data Quality Summary

In [17]:
summary = {
    'Check': ['Missing Values', 'Duplicate Records', 'Invalid Categories', 'Range Validation', 'Logical Consistency'],
    'Result': [0, 0, 'Not Found', 'Passed', 'Passed']
}

data_summary = pd.DataFrame(summary)
print(data_summary)

                 Check     Result
0       Missing Values          0
1    Duplicate Records          0
2   Invalid Categories  Not Found
3     Range Validation     Passed
4  Logical Consistency     Passed

- The dataset successfully passed all major data quality checks, including completeness, uniqueness, data type validation, category consistency, range validation, and logical consistency. No significant issues were identified that would impact the reliability of subsequent analysis. Therefore, the dataset is considered suitable for exploratory data analysis, statistical testing, and predictive modeling.

## Now it's time to perform EDA